### PR TITLE
Turbolinks iOS and Android app support

### PR DESCRIPTION
**Pull request by danielwestendorf**
First pass of changes required to support iOS and Android apps. Probably more to come as the apps evolve.

### CODE REVIEW

**Comment by Shpigford** [comment]
Do you need this merged in to master to keep making progress on the iOS/Android apps?

**Comment by danielwestendorf** [comment]
Nope, not yet. I've got discussion points over at #10 as well as https://github.com/danielwestendorf/Droptune-iOS/issues

**Comment by danielwestendorf** [comment]
I'm confident this is in a good enough place to merge and deploy. Any additional changes backend will probably be around UI/UIX.

**Comment by danielwestendorf** [comment]
@Shpigford forgot to tag you above.

**Pull request merged**
